# Generated by Django 4.1.13 on 2023-12-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название курса')),
                ('prevew', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='превью')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Leson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название урока')),
                ('prevew', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='превью')),
                ('description', models.TextField(verbose_name='описание')),
                ('video', models.URLField(verbose_name='ссылка на видео')),
                ('сourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
